#!/usr/bin/env node
/**
 * iOS App Factory — First-Run Setup Wizard
 *
 * Guides the user through every credential and auth step exactly once.
 * After this runs successfully, the factory is fully autonomous.
 *
 * Steps:
 *   1. .env file — create if missing, fill in any blanks
 *   2. EAS CLI login (eas whoami)
 *   3. Apple Developer session — eas submit creates/validates it with full 2FA inline
 *   4. First build credentials — distribution cert + provisioning profile
 *   5. First app on ASC — eas submit creates it interactively, caches ascAppId
 *   6. Write setup.json completion record
 *
 * Run: node scripts/setup.js
 * Or:  node scripts/setup.js --check   (just check status, no prompts)
 */

const fs   = require('fs');
const path = require('path');
const readline = require('readline');
const { spawn, execSync } = require('child_process');

const ROOT       = path.join(__dirname, '..');
const ENV_PATH   = path.join(ROOT, '.env');
const SETUP_PATH = path.join(ROOT, '.setup-complete.json');

// ─── ANSI ─────────────────────────────────────────────────────────────────────
const C = {
  reset: '\x1b[0m', bold: '\x1b[1m', dim: '\x1b[2m',
  red: '\x1b[31m', green: '\x1b[32m', yellow: '\x1b[33m',
  blue: '\x1b[34m', cyan: '\x1b[36m', white: '\x1b[37m',
  gray: '\x1b[90m', brightGreen: '\x1b[92m', brightCyan: '\x1b[96m',
  brightWhite: '\x1b[97m', brightYellow: '\x1b[93m', magenta: '\x1b[35m',
};

const ok   = (s) => console.log(`  ${C.brightGreen}✓${C.reset}  ${s}`);
const fail = (s) => console.log(`  ${C.red}✗${C.reset}  ${s}`);
const info = (s) => console.log(`  ${C.cyan}→${C.reset}  ${s}`);
const warn = (s) => console.log(`  ${C.yellow}!${C.reset}  ${s}`);
const head = (s) => console.log(`\n${C.bold}${C.brightCyan}${s}${C.reset}`);
const rule = ()  => console.log(`${C.gray}${'─'.repeat(60)}${C.reset}`);

// ─── ENV ──────────────────────────────────────────────────────────────────────
function loadEnv() {
  if (!fs.existsSync(ENV_PATH)) return {};
  const env = {};
  fs.readFileSync(ENV_PATH, 'utf8').split('\n').forEach(l => {
    const m = l.match(/^([^#=\s][^=]*)=(.+)/);
    if (m) env[m[1].trim()] = m[2].trim();
  });
  return env;
}

function saveEnv(env) {
  const lines = Object.entries(env)
    .filter(([, v]) => v)
    .map(([k, v]) => `${k}=${v}`);
  const header = [
    '# iOS App Factory — Environment',
    '# Generated by setup.js — edit manually or re-run: node scripts/setup.js',
    '',
    '# LLM (OpenRouter)',
    '',
  ];
  const appleSection = [
    '',
    '# Apple / EAS',
    '# EXPO_ prefixed vars are read natively by eas-cli',
    '',
  ];
  const openrouter = lines.filter(l => l.startsWith('OPENROUTER'));
  const apple = lines.filter(l => !l.startsWith('OPENROUTER'));
  fs.writeFileSync(ENV_PATH, [...header, ...openrouter, ...appleSection, ...apple].join('\n') + '\n');
}

// ─── PROMPTS ─────────────────────────────────────────────────────────────────
function prompt(question, defaultVal = '') {
  return new Promise(resolve => {
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    const display = defaultVal ? `${question} ${C.gray}[${defaultVal}]${C.reset} ` : `${question} `;
    rl.question(display, ans => {
      rl.close();
      resolve(ans.trim() || defaultVal);
    });
  });
}

function promptSecret(question) {
  return new Promise(resolve => {
    process.stdout.write(question + ' ');
    process.stdin.setRawMode(true);
    process.stdin.resume();
    process.stdin.setEncoding('utf8');
    let val = '';
    const onData = key => {
      if (key === '\r' || key === '\n') {
        process.stdin.setRawMode(false);
        process.stdin.pause();
        process.stdin.removeListener('data', onData);
        process.stdout.write('\n');
        resolve(val);
      } else if (key === '\u0003') {
        process.exit(0);
      } else if (key === '\u007f') {
        if (val.length > 0) { val = val.slice(0, -1); process.stdout.write('\b \b'); }
      } else {
        val += key;
        process.stdout.write('*');
      }
    };
    process.stdin.on('data', onData);
  });
}

// ─── SPAWN (inherits stdio — required for interactive auth) ───────────────────
function spawnInherited(cmd, args, opts = {}) {
  return new Promise((resolve) => {
    const proc = spawn(cmd, args, {
      cwd: opts.cwd || ROOT,
      stdio: 'inherit',
      env: { ...process.env, ...opts.env },
    });
    proc.on('close', code => resolve({ ok: code === 0, code }));
    proc.on('error', e => resolve({ ok: false, code: -1, error: e.message }));
  });
}

function spawnCapture(cmd, args, opts = {}) {
  return new Promise((resolve) => {
    let out = '', err = '';
    const proc = spawn(cmd, args, {
      cwd: opts.cwd || ROOT,
      stdio: ['ignore', 'pipe', 'pipe'],
      env: { ...process.env, ...opts.env },
    });
    proc.stdout.on('data', d => out += d);
    proc.stderr.on('data', d => err += d);
    proc.on('close', code => resolve({ ok: code === 0, stdout: out.trim(), stderr: err.trim() }));
    proc.on('error', e => resolve({ ok: false, stdout: '', stderr: e.message }));
  });
}

// ─── CHECKS ──────────────────────────────────────────────────────────────────
function checkSetupComplete() {
  if (!fs.existsSync(SETUP_PATH)) return null;
  try { return JSON.parse(fs.readFileSync(SETUP_PATH, 'utf8')); } catch { return null; }
}

function markComplete(data) {
  fs.writeFileSync(SETUP_PATH, JSON.stringify({ ...data, completedAt: new Date().toISOString() }, null, 2));
}

async function checkEASLogin() {
  const r = await spawnCapture('npx', ['eas', 'whoami']);
  return r.ok ? r.stdout.trim() : null;
}

async function checkAppleSession(appleId) {
  const sessionPath = path.join(process.env.HOME, '.app-store', 'auth', appleId, 'cookie');
  return fs.existsSync(sessionPath);
}

// ─── STATUS DISPLAY ───────────────────────────────────────────────────────────
async function printStatus() {
  head('iOS App Factory — Setup Status');
  rule();

  const env = loadEnv();
  const setup = checkSetupComplete();

  // Credentials
  const creds = [
    ['OPENROUTER_API_KEY',          'OpenRouter API key'],
    ['APPLE_ID',                    'Apple ID'],
    ['EXPO_APPLE_TEAM_ID',          'Apple Team ID'],
    ['EXPO_ASC_KEY_ID',             'ASC API Key ID'],
    ['EXPO_ASC_ISSUER_ID',          'ASC Issuer ID'],
    ['EXPO_ASC_API_KEY_PATH',       'ASC .p8 Key File'],
    ['EXPO_APPLE_APP_SPECIFIC_PASSWORD', 'App-Specific Password'],
  ];

  console.log(`\n  ${C.bold}Credentials (.env)${C.reset}`);
  for (const [key, label] of creds) {
    if (env[key]) {
      const preview = key.includes('PASSWORD') || key.includes('KEY')
        ? env[key].slice(0, 4) + '****'
        : env[key];
      ok(`${label}: ${C.gray}${preview}${C.reset}`);
    } else {
      fail(`${label}: ${C.red}missing${C.reset}`);
    }
  }

  if (env.EXPO_ASC_API_KEY_PATH && !fs.existsSync(env.EXPO_ASC_API_KEY_PATH)) {
    fail(`.p8 file not found at ${env.EXPO_ASC_API_KEY_PATH}`);
  }

  // EAS login
  console.log(`\n  ${C.bold}EAS Account${C.reset}`);
  const easUser = await checkEASLogin();
  easUser ? ok(`Logged in as: ${C.brightWhite}${easUser}${C.reset}`) : fail('Not logged in to EAS');

  // Apple session
  if (env.APPLE_ID) {
    console.log(`\n  ${C.bold}Apple Developer Session${C.reset}`);
    const hasSession = await checkAppleSession(env.APPLE_ID);
    hasSession
      ? ok('Session cookie exists (may still be expired)')
      : warn('No local session — will prompt for 2FA on first submit');
  }

  // Setup record
  console.log(`\n  ${C.bold}First-Run Completion${C.reset}`);
  if (setup) {
    ok(`Setup completed: ${C.gray}${setup.completedAt}${C.reset}`);
    if (setup.firstAppSlug) ok(`First app slug: ${C.brightWhite}${setup.firstAppSlug}${C.reset}`);
    if (setup.easUsername)  ok(`EAS user: ${C.brightWhite}${setup.easUsername}${C.reset}`);
  } else {
    warn('Setup not completed — run: node scripts/setup.js');
  }

  rule();
}

// ─── WIZARD STEPS ─────────────────────────────────────────────────────────────
async function stepEnv() {
  head('Step 1 — Credentials');
  rule();
  console.log(`  We need a few keys to build and ship apps. These are stored in ${C.brightWhite}.env${C.reset} (never committed).\n`);

  const env = loadEnv();
  let changed = false;

  async function ask(key, label, hint, secret = false) {
    if (env[key]) { ok(`${label} already set`); return; }
    info(hint);
    const val = secret
      ? await promptSecret(`  ${C.brightWhite}${label}:${C.reset}`)
      : await prompt(`  ${C.brightWhite}${label}:${C.reset}`);
    if (val) { env[key] = val; changed = true; }
    else warn(`Skipped ${label} — some features may not work`);
  }

  await ask('OPENROUTER_API_KEY', 'OpenRouter API Key',
    'Get one free at openrouter.ai — used for LLM idea generation');
  await ask('APPLE_ID', 'Apple ID (email)',
    'Your Apple Developer account email');
  await ask('EXPO_APPLE_TEAM_ID', 'Apple Team ID',
    'Find it at developer.apple.com → Membership → Team ID (e.g. 87W64WD9U4)');
  await ask('EXPO_ASC_KEY_ID', 'ASC API Key ID',
    'Create at appstoreconnect.apple.com → Users → Integrations → Keys (e.g. FGRYRP853Z)');
  await ask('EXPO_ASC_ISSUER_ID', 'ASC Issuer ID',
    'Shown at the top of the ASC Keys page (UUID format)');

  if (!env.EXPO_ASC_API_KEY_PATH) {
    info('Download the .p8 file from the ASC Keys page (can only download once)');
    const p8 = await prompt(`  ${C.brightWhite}Path to .p8 file:${C.reset}`, `${process.env.HOME}/.appstoreconnect/private_keys/AuthKey_${env.EXPO_ASC_KEY_ID || 'KEYID'}.p8`);
    if (p8) {
      env.EXPO_ASC_API_KEY_PATH = p8;
      changed = true;
      // Ensure directory exists
      fs.mkdirSync(path.dirname(p8), { recursive: true });
    }
  } else {
    ok('ASC .p8 key path already set');
  }

  await ask('EXPO_APPLE_APP_SPECIFIC_PASSWORD', 'App-Specific Password',
    'Generate at appleid.apple.com → Security → App-Specific Passwords (used to create new apps on ASC)', true);

  if (changed) {
    saveEnv(env);
    ok('.env saved');
  }

  // Reload into process.env
  Object.assign(process.env, env);
  return env;
}

async function stepEASLogin() {
  head('Step 2 — EAS Account');
  rule();
  console.log('  EAS builds your app in the cloud and handles certificates automatically.\n');

  const user = await checkEASLogin();
  if (user) { ok(`Already logged in as ${C.brightWhite}${user}${C.reset}`); return user; }

  info('Logging in to Expo / EAS...');
  await spawnInherited('npx', ['eas', 'login']);

  const user2 = await checkEASLogin();
  if (user2) { ok(`Logged in as ${C.brightWhite}${user2}${C.reset}`); return user2; }
  fail('EAS login failed — try: npx eas login');
  return null;
}

async function stepFirstBuild(env) {
  head('Step 3 — Apple Certificates + First Build');
  rule();
  console.log('  We need to register your bundle ID and set up code signing.');
  console.log('  This only runs once. EAS will create and manage certificates automatically.\n');
  console.log(`  ${C.yellow}IMPORTANT: If asked to revoke certificates, press ${C.bold}N${C.reset}${C.yellow}.${C.reset}`);
  console.log(`  ${C.yellow}You can have at most 3 distribution certificates.${C.reset}\n`);

  // Use a known-good test slug or pick from existing apps
  const appsDir = path.join(ROOT, 'apps');
  let testSlug = 'mythology-travel-planner';
  if (!fs.existsSync(path.join(appsDir, testSlug))) {
    const apps = fs.existsSync(appsDir) ? fs.readdirSync(appsDir) : [];
    testSlug = apps[0] || null;
  }

  if (!testSlug) {
    warn('No apps found — run the factory first to generate an app, then re-run setup for TestFlight');
    return null;
  }

  const appDir = path.join(appsDir, testSlug);
  info(`Using app: ${C.brightWhite}${testSlug}${C.reset}`);

  // Ensure eas.json
  if (!fs.existsSync(path.join(appDir, 'eas.json'))) {
    fs.copyFileSync(path.join(ROOT, 'config', 'eas.json'), path.join(appDir, 'eas.json'));
  }

  // Ensure git repo
  if (!fs.existsSync(path.join(appDir, '.git'))) {
    execSync('git init -q && git add -A && git commit -q -m "setup"', { cwd: appDir, stdio: 'ignore' });
  }

  // Check if already has a successful build
  const buildList = await spawnCapture('npx', ['eas', 'build:list', '--platform', 'ios', '--limit', '1', '--non-interactive'], { cwd: appDir });
  if (buildList.stdout.includes('finished')) {
    ok('Already have a successful build — skipping build step');
    return testSlug;
  }

  info('Starting EAS build — this takes ~5 minutes (first time sets up signing)...');
  info('If asked to revoke certificates, press N');
  const buildR = await spawnInherited('npx', ['eas', 'build', '--platform', 'ios', '--profile', 'production'], { cwd: appDir });

  if (buildR.ok) {
    ok('Build completed');
    return testSlug;
  } else {
    warn('Build failed or exited — check output above');
    return testSlug;
  }
}

async function stepFirstSubmit(slug, env) {
  head('Step 4 — TestFlight — First Submission');
  rule();
  console.log('  Submitting to TestFlight. EAS will log in to Apple and create the app on App Store Connect.');
  console.log(`  ${C.yellow}You will be asked for your Apple ID password and a 6-digit 2FA code.${C.reset}`);
  console.log('  This is the last time you will need to do this — the session will be cached.\n');

  const appDir = path.join(ROOT, 'apps', slug);

  // Check if ascAppId already set
  const easJson = JSON.parse(fs.readFileSync(path.join(appDir, 'eas.json'), 'utf8'));
  if (easJson.submit?.production?.ios?.ascAppId) {
    ok(`ascAppId already cached: ${easJson.submit.production.ios.ascAppId}`);
    info('Running non-interactive submit...');
    const r = await spawnInherited('npx', ['eas', 'submit', '--platform', 'ios', '--latest', '--non-interactive'], { cwd: appDir });
    return r.ok;
  }

  info('Running interactive submit — Apple will send a 2FA code to your device or SMS...');
  const r = await spawnInherited('npx', ['eas', 'submit', '--platform', 'ios', '--latest'], { cwd: appDir });

  if (r.ok) {
    ok('Submitted to TestFlight');
    // Try to cache the ascAppId now that the app exists
    const { findApp } = require(path.join(ROOT, 'orchestrator', 'asc-api'));
    const appJson = JSON.parse(fs.readFileSync(path.join(appDir, 'app.json'), 'utf8'));
    const bundleId = appJson.expo?.ios?.bundleIdentifier;
    if (bundleId) {
      const app = await findApp(bundleId);
      if (app.found) {
        const eas = JSON.parse(fs.readFileSync(path.join(appDir, 'eas.json'), 'utf8'));
        eas.submit = eas.submit || {};
        eas.submit.production = eas.submit.production || {};
        eas.submit.production.ios = eas.submit.production.ios || {};
        eas.submit.production.ios.ascAppId = app.id;
        eas.submit.production.ios.appleId = env.APPLE_ID;
        fs.writeFileSync(path.join(appDir, 'eas.json'), JSON.stringify(eas, null, 2));
        execSync('git add -A && git commit -q -m "cache ascAppId" --allow-empty', { cwd: appDir, stdio: 'ignore' });
        ok(`ascAppId cached: ${C.brightWhite}${app.id}${C.reset} — future submits are fully automated`);
      }
    }
    return true;
  } else {
    warn('Submit failed or exited — check output above');
    info('You can retry with: cd apps/' + slug + ' && npx eas submit --platform ios --latest');
    return false;
  }
}

// ─── MAIN ─────────────────────────────────────────────────────────────────────
async function main() {
  const checkOnly = process.argv.includes('--check');

  console.log(`\n${C.bold}${C.magenta}╔══════════════════════════════════════════════════╗${C.reset}`);
  console.log(`${C.bold}${C.magenta}║  iOS App Factory — Setup Wizard                  ║${C.reset}`);
  console.log(`${C.bold}${C.magenta}╚══════════════════════════════════════════════════╝${C.reset}`);

  if (checkOnly) {
    await printStatus();
    return;
  }

  const existing = checkSetupComplete();
  if (existing && !process.argv.includes('--force')) {
    console.log(`\n${C.brightGreen}Setup already complete${C.reset} (${existing.completedAt})`);
    console.log(`  Run ${C.brightWhite}node scripts/setup.js --check${C.reset} to view status`);
    console.log(`  Run ${C.brightWhite}node scripts/setup.js --force${C.reset} to redo setup`);
    console.log(`  Run ${C.brightWhite}node tui.js --run --llm${C.reset} to start the factory\n`);
    return;
  }

  // Step 1: Credentials
  const env = await stepEnv();

  // Step 2: EAS login
  const easUser = await stepEASLogin();

  // Step 3: First build (sets up certificates)
  const slug = await stepFirstBuild(env);

  // Step 4: First submit (creates ASC app, gets 2FA, caches session)
  let submitted = false;
  if (slug) {
    submitted = await stepFirstSubmit(slug, env);
  }

  // Done
  head('Setup Complete');
  rule();
  markComplete({ easUsername: easUser, firstAppSlug: slug, submitted });

  if (submitted) {
    ok(`${C.bold}${C.brightGreen}App submitted to TestFlight!${C.reset}`);
    info('Apple sends an email when it\'s ready. Usually 5-30 minutes.');
    info('Open TestFlight on your iPhone and look for the app.');
  }

  console.log(`\n  ${C.bold}What's next:${C.reset}`);
  info(`Launch the factory:  ${C.brightWhite}node tui.js --run --llm${C.reset}`);
  info(`Full pipeline:       ${C.brightWhite}node tui.js --run --full${C.reset}`);
  info(`Check status:        ${C.brightWhite}node scripts/setup.js --check${C.reset}`);
  console.log();
}

main().catch(e => {
  console.error(`\n${C.red}Fatal error:${C.reset}`, e.message);
  process.exit(1);
});
